### ISSUE TITLE
app.js error when find a code

### ISSUE THREAD

**Issue by Yunikee** [Tenclea/YANG#1]
Hi, so, when the program finds a valid code, it doest show on discord webhook and claim.

When i check the cmd it shows this: https://prnt.sc/10jvmjh

obs:  This build seems to be very good!

**Comment by Tenclea** [comment]
Hi, first of all thank you for your feedback !
Was the code really working ? Did you input your token correctly ?
I will have to check what could have possibly gone wrong, and let you know when I find out !

**Comment by Tenclea** [comment]
I pushed a potential fix to your issue, let me know if this occurs once again

**Comment by Yunikee** [comment]
> Hi, first of all thank you for your feedback !
> Was the code really working ? Did you input your token correctly ?
> I will have to check what could have possibly gone wrong, and let you know when I find out !

Yes, i put everything right, let me know when you fix please and yes, the code are working fine i guess, the webhook are sending the "start" message fine but the error is when if found a code shows that error

**Comment by Yunikee** [comment]
> I pushed a potential fix to your issue, let me know if this occurs once again

Checking!

**Comment by Tenclea** [comment]
Closed until further notice
