### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by variablenine** [Tenclea/YANG#109]
I have Avast downloaded on my PC and I have gotten this popup multiple times. Should this be an issue?

![image](https://user-images.githubusercontent.com/103234275/213625095-be17adb8-3d78-4c9b-9567-2d7c1abadc89.png)

**Comment by variablenine** [comment]
It says its a phishing attempt

**Comment by Tenclea** [comment]
Avast - like many other antiviruses - can be paid to flag certain URLs or files as dangerous, it is far from a great antivirus
In your case, it could be that one of the proxies got blocked while attempting to contact the Discord's servers as displayed in the popup
