### ISSUE TITLE
idk why when i run it on linux server it didn't work as windows

### ISSUE THREAD

**Issue by alimawla69** [Tenclea/YANG#113]
/root/.pm2/logs/app-error.log last 15 lines:
1|app      | /root/dd/app.js:88
1|app      |                            if (!body?.message && !body?.subscription_plan) {
1|app      |                                      ^
1|app      |
1|app      | SyntaxError: Unexpected token .
1|app      |     at Module._compile (internal/modules/cjs/loader.js:723:23)
1|app      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
1|app      |     at Module.load (internal/modules/cjs/loader.js:653:32)
1|app      |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
1|app      |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
1|app      |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
1|app      |     at Module._compile (internal/modules/cjs/loader.js:778:30)
1|app      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
1|app      |     at Module.load (internal/modules/cjs/loader.js:653:32)
1|app      |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by Tenclea** [comment]
Your NodeJS version is outdated, you need to update to v16+.
