### ISSUE TITLE
Windows Defender detected this application as Trojan:Script/Wacatac.H!ml

### ISSUE THREAD

**Issue by Fortress937** [Tenclea/YANG#118]
**Windows Security detected this application as Trojan:Script/Wacatac.H!ml**

When i run this application using Node.js, they detected this as virus.

![Screenshot 2023-04-10 110726](https://user-images.githubusercontent.com/119410273/230817565-0444a8e5-89e8-4834-bd0a-ddeca3f30493.png)

Anyway to fix this? even it was already in Exclusion list.

**Comment by Fortress937** [comment]
Although sounds like a false positive, but it's very overwhelming to see windows security detecting threats even it was already in Exclusions.

And also afraid if it may cause conflict with other important or personal stuff...

**Comment by Tenclea** [comment]
What exactly happened here? Did you use the compiled version or the source code ? What file(s) are flagged as dangerous ? @Fortress937

**Comment by Fortress937** [comment]
> What exactly happened here? Did you use the compiled version or the source code ? What file(s) are flagged as dangerous ? @Fortress937

this happen when i run this application according from the release section. i can tell it was a complied version of it.
![image](https://user-images.githubusercontent.com/119410273/230916755-88f28ccd-1b1b-4d49-8471-b4d722e683ba.png)

**Comment by Tenclea** [comment]
Does the same problem arise using an earlier release of the program ?

**Comment by Tenclea** [comment]
I can't seem to be able to reproduce the issue :/ i will try to look into it, but i really don't know what it could be

**Comment by Tenclea** [comment]
Virustotal only detects the program as malicious once (which is usually false-positive): https://www.virustotal.com/gui/file/770a5ff96b3b10d4bea735d6e673cca4b34cb7abea20193668cf07bdb629d42b

**Comment by Tenclea** [comment]
Does the detection happen before running the file, or when running it ?

**Comment by Fortress937** [comment]
> Does the detection happen before running the file, or when running it ?

happen while running it
yeah, i tried using windows defender custom scan, and scanned this application and found no threats, but when running especially executing, the windows defender start detecting threats again.

**Comment by Tenclea** [comment]
I've uploaded a new release for the windows version, could you try it out ?
https://github.com/Tenclea/YANG/releases/tag/v3.2.0

**Comment by Tenclea** [comment]
😭

**Comment by Tenclea** [comment]
I've tried something else, does it run fine for you this time ?
https://github.com/Tenclea/YANG/releases/tag/v3.2.0

**Comment by Fortress937** [comment]
![image](https://user-images.githubusercontent.com/119410273/230933897-bb528c1d-43ed-4137-a0f8-78ebed759705.png)
i think it still the same :/  but i noticed some solution

**Comment by Fortress937** [comment]
![image](https://user-images.githubusercontent.com/119410273/230934407-c2ad6bd0-258c-4ec2-aad3-6aaafca4f4ef.png)
but when i closed an executable application, it return normal and the application is not being removed from devices.
