### ISSUE TITLE
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### ISSUE THREAD

**Issue by Tekkiii** [Tenclea/YANG#147]
dk why this is happening

**Comment by Tenclea** [comment]
?? Could you provide a full description of your issue as well as an error log ?

**Comment by Tekkiii** [comment]
![image](https://github.com/Tenclea/YANG/assets/140958230/6f8005bc-dcbc-4607-b5c4-2813ae70fac9)

**Comment by Tenclea** [comment]
Your config file is too old. Delete it, and let the program recreate one for you.
