### ISSUE TITLE
'Fingerprint' Undefined.

### ISSUE THREAD

**Issue by code9855** [Tenclea/YANG#15]
There were a lot of '?', rectifying those, I got the project to run.
But I get 'fingerprint' undefined.
Help would be appreciated.

**Comment by Tenclea** [comment]
Can you provide some screenshots of the actual error ? It's very hard to understand, or to fix anything without them

**Comment by code9855** [comment]
Yeah, I'll attach it.
P•S Have you ever come across a working nitro code with this method? Because it's a pretty low probability of finding one.

**Comment by Tenclea** [comment]
> Yeah, I'll attach it.
> P•S Have you ever come across a working nitro code with this method? Because it's a pretty low probability of finding one.

I found a couple ones with a friend, and am always working to try to improve the generator

**Comment by 0x4x41** [comment]
> There were a lot of '?', rectifying those, I got the project to run.
> But I get 'fingerprint' undefined.
> Help would be appreciated.

just add a try catch around it

so replace

if (res.body.fingerprint) {
                    checked.push(p);
                }
                
with 

            try {
                if (res.body.fingerprint) {
                    checked.push(p);
                }
            } catch {

**Comment by Tenclea** [comment]
Oh, i think I just understood what the initial issue was  
@code9855 you should try to update your node.js version to 14.x at least

**Comment by code9855** [comment]
Okay.

**Comment by code9855** [comment]
> > There were a lot of '?', rectifying those, I got the project to run.
> > But I get 'fingerprint' undefined.
> > Help would be appreciated.
> 
> just add a try catch around it
> 
> so replace
> 
> if (res.body.fingerprint) {
> checked.push(p);
> }
> 
> with
> 
> ```
>         try {
>             if (res.body.fingerprint) {
>                 checked.push(p);
>             }
>         } catch {
> ```

Where should I close the { after the catch?

**Comment by code9855** [comment]
Thanks for the help. Got it working.
