### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by Galin08** [Tenclea/YANG#153]
I think I have a problem and I will be very grateful if you help me. The problem is the following since 24 hours it works but I don't have nitro this is what it says as a problem: 
18:30:20 [DEBUG] » Connection to http://24.152.50.116:999 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:20 [DEBUG] » Connection to http://124.105.3.214:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:20 [DEBUG] » Connection to http://181.212.41.172:999 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:20 [DEBUG] » Connection to http://172.104.167.148:3128 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:20 [DEBUG] » Connection to http://170.83.242.250:999 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:20 [DEBUG] » Connection to http://87.103.133.243:4444 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:20 [DEBUG] » Connection to http://118.99.96.173:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:20 [DEBUG] » Connection to http://103.124.97.12:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:20 [DEBUG] » Connection to http://103.165.157.87:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:20 [DEBUG] » Connection to http://24.152.50.116:999 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:20 [DEBUG] » Connection to http://154.236.179.226:1981 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:20 [DEBUG] » Connection to http://20.219.182.59:3129 failed : connect ECONNREFUSED 20.219.182.59:3129.
18:30:21 [DEBUG] » Connection to http://204.157.241.203:999 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:21 [DEBUG] » Connection to http://176.98.234.124:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:21 [DEBUG] » Connection to http://103.165.150.118:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:21 [WARN] » pHrkl8awGC5aY7c2 was an invalid gift code.
18:30:21 [DEBUG] » Connection to http://72.10.160.90:2393 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:21 [DEBUG] » Connection to http://167.250.50.242:999 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:21 [DEBUG] » Connection to http://76.169.129.241:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:21 [DEBUG] » Connection to http://190.128.225.117:999 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:21 [WARN] » 1ZXkxNGytbDzbXnx was an invalid gift code.
18:30:21 [DEBUG] » Connection to http://5.17.6.83:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:21 [DEBUG] » Connection to http://110.34.3.229:3128 failed : socket hang up.
18:30:21 [DEBUG] » Connection to http://72.10.160.90:16487 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:22 [DEBUG] » Connection to http://202.154.18.9:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:22 [DEBUG] » Connection to http://20.44.189.184:3129 failed : connect ECONNREFUSED 20.44.189.184:3129.
18:30:22 [DEBUG] » Connection to http://62.182.201.75:8765 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:22 [DEBUG] » Connection to http://161.18.244.14:999 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:22 [DEBUG] » Connection to http://67.43.228.253:15545 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:22 [DEBUG] » Connection to http://67.43.236.20:25621 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:22 [DEBUG] » Connection to http://67.43.227.227:24843 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:22 [DEBUG] » Connection to http://61.7.146.7:80 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:22 [DEBUG] » Connection to http://202.69.38.82:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:22 [DEBUG] » Connection to http://92.124.149.12:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:22 [DEBUG] » Connection to http://72.10.160.90:2413 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:23 [DEBUG] » Connection to http://103.245.204.214:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:23 [DEBUG] » Connection to http://203.190.44.147:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:23 [WARN] » kjRgMB3MQHcaMFSR was an invalid gift code.
18:30:23 [DEBUG] » Connection to http://190.107.236.171:999 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:23 [DEBUG] » Connection to http://38.49.138.205:999 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:23 [DEBUG] » Connection to http://159.192.132.149:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:23 [DEBUG] » Connection to http://185.255.46.121:8080 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:23 [DEBUG] » Connection to http://5.165.6.188:1513 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:23 [DEBUG] » Connection to http://177.93.45.154:999 failed : A "socket" was not created for HTTP request before 5000ms.
18:30:23 [WARN] » s1sRSdNW7XA10jLF was an invalid gift code.

I could be wrong, but I doubt it.
![image](https://github.com/Tenclea/YANG/assets/142357364/31d3318f-a06b-4904-8c67-24856fd7a605)
![image](https://github.com/Tenclea/YANG/assets/142357364/a1a53a0a-be8d-40f9-8b97-926b4406ccd3)
I have put from working_proxies.txt in http-proxies.txt, I may be confusing something there, but you will tell. what to do

**Comment by Galin08** [comment]
@Tenclea

**Comment by Tenclea** [comment]
Two things:
- You have the debug mode activated, it is often helpful to identify issues in the app logic or in configuration files. If you disable it, the timeouts you see (which are perfectly normal) will be hidden.

- Seeing that many errors is kinda suspicious. If your internet connection/cpu are not that fast, I'd suggest lowering the amount of threads in the config file. Try 50 at first and check again if you get as many errors. (You should still have some, but not as many)

**Comment by Galin08** [comment]
Аfter editing, maybe it's like that again, you say, sir. and does it work properly because for 1 day I don't have any nitro. Аnd for the debug mode i ran it because it doesn't give me codes. After the editing, maybe it's like that again, you say, sir. and does it work properly because i have no nitro for 1 day. And for the debug mode I ran it because it's not giving me codes and I can't figure out why. My cpu is i5 12500h; 32 GB of RAM; nvidia 4060. How long on average it gives a valid code. Because I have nothing for so long. And is this normal?

![image](https://github.com/Tenclea/YANG/assets/142357364/a6eb02cd-4856-4ce4-ae58-665de38615a0)
![image](https://github.com/Tenclea/YANG/assets/142357364/4113dee7-de2e-4732-8f98-06c093646029)
![image](https://github.com/Tenclea/YANG/assets/142357364/340f55b5-e384-4241-8deb-ce259293d872)
@Tenclea

**Comment by Tenclea** [comment]
Read this: https://github.com/Tenclea/YANG/discussions/62

**Comment by Galin08** [comment]
what proxies to use: 
Rotating Residential
Static Residential
Datacenter

**Comment by Tenclea** [comment]
any that are fast and hide your ip

**Comment by Galin08** [comment]
I bought the proxies where to put them
