### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dylanprice1207** [Tenclea/YANG#16]
![image](https://user-images.githubusercontent.com/80633524/118364035-bdd88800-b58e-11eb-99e7-721ea0161c86.png)

**Comment by Tenclea** [comment]
> ![image](https://user-images.githubusercontent.com/80633524/118364035-bdd88800-b58e-11eb-99e7-721ea0161c86.png)
> 

@dylanprice1207 you might need to update your nodejs version to v14 at least
