### ISSUE TITLE
Proxies : -76 & Error: socket hang up

### ISSUE THREAD

**Issue by marat2509** [Tenclea/YANG#23]
Bug 1: 
![Screenshot_2021-06-05-13-06-24-841_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120888264-fdc7e380-c5ff-11eb-83b1-ddbc35555363.jpg)

Error 1 (Personally, after such errors, nitro mining stops): 
![Screenshot_2021-06-05-02-17-40-658_com microsoft rdc     ####androidx](https://user-images.githubusercontent.com/52219238/120888288-1fc16600-c600-11eb-8dab-1312c031f820.jpg)

**Comment by Tenclea** [comment]
I think i know how to fix the error, but i have no idea what might have happened for you to get a negative proxies amount 🤔  
I will do some testing on my own, can you send me your configuration of the generator ? (without your token and webhook ofc)

**Comment by marat2509** [comment]
{
	"debugMode": false,
	"redeemToken": "TOKEN",
	"saveWorkingProxies": true,
	"scrapeProxies": true,
	"threads": 1000,
	"webhookUrl": "URL"
}

**Comment by Tenclea** [comment]
Thanks, do you know for how long the program was running ?

**Comment by marat2509** [comment]
From the solution options, I think you can do that when the number of proxies is negative, so that the script will re-parse new proxies, check them and start over without resetting the counters

**Comment by marat2509** [comment]
10 hours

**Comment by Tenclea** [comment]
> 
> 
> From the solution options, I think you can do that when the number of proxies is negative, so that the script will re-parse new proxies, check them and start over without resetting the counters

well actually, it should already be parsing some every 60 minutes 🤔

**Comment by Tenclea** [comment]
> 
> 
> 10 hours

Alright, i'll be doing some testing, thanks for the reports and your time

**Comment by marat2509** [comment]
After fix (https://github.com/Tenclea/YANG/commit/504c9006c3e7cdc275476ebd271ff9e190a966b9) the situation has changed a little, but still, after an error, the mining stops

![Screenshot_2021-06-05-14-36-53-611_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120890504-c4957080-c60b-11eb-8e30-fb7c08ea27ce.jpg)

**Comment by Tenclea** [comment]
> After fix (https://github.com/Tenclea/YANG/commit/504c9006c3e7cdc275476ebd271ff9e190a966b9) the situation has changed a little, but still, after an error, the mining stops
> 
> ![Screenshot_2021-06-05-14-36-53-611_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120890504-c4957080-c60b-11eb-8e30-fb7c08ea27ce.jpg)
> 

Actually, it seems like it stops before checking for updates and that something is causing the request to freeze 🤔  
Can you try to disable the proxy scrapper in the config and tell me how it goes ?

**Comment by marat2509** [comment]
> > After fix ([504c900](https://github.com/Tenclea/YANG/commit/504c9006c3e7cdc275476ebd271ff9e190a966b9)) the situation has changed a little, but still, after an error, the mining stops
> > ![Screenshot_2021-06-05-14-36-53-611_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120890504-c4957080-c60b-11eb-8e30-fb7c08ea27ce.jpg)
> 
> Actually, it seems like it stops before checking for updates and that something is causing the request to freeze 🤔
> Can you try to disable the proxy scrapper in the config and tell me how it goes ?

Could you give me a proxy, or I can run without a proxy?

**Comment by Tenclea** [comment]
Leave the proxies in working_proxies.txt, they should automatically be used into the bot

**Comment by marat2509** [comment]
![Screenshot_2021-06-05-15-21-54-275_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120891540-d1b55e00-c611-11eb-90be-c567b03ec51a.jpg)


Output with scrapeProxy:true and debug mode: https://pastebin.com/g16cMB7L

**Comment by Tenclea** [comment]
Did it stop working in the paste you sent ?

**Comment by marat2509** [comment]
> Did it stop working in the paste you sent ?

Yes it didn't work

**Comment by Tenclea** [comment]
I'm pushing a new update, let me know if it works

**Comment by marat2509** [comment]
Wait

**Comment by marat2509** [comment]
It **seems** to work, but every other time, I'll try to test it again, and just in case I'll try to install VPN

**Comment by marat2509** [comment]
It works every other time, then like this: https://pastebin.com/giQkwCkX, then like this, after a while it just stops
![Screenshot_2021-06-05-19-12-03-721_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120898078-1224d400-c632-11eb-86e5-e8c409069b97.jpg)

**Comment by marat2509** [comment]
The situation does not change with or without VPN

**Comment by marat2509** [comment]
After a while, the process resumed, but very few proxies remained, although there were about 1000

![Screenshot_2021-06-05-19-43-09-402_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120899045-6631b780-c636-11eb-8a15-e016ce732932.jpg)

**Comment by marat2509** [comment]
After freezing, it continues to work, but the number of proxies is significantly reduced
![Screenshot_2021-06-05-20-18-19-469_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120900017-4c46a380-c63b-11eb-9064-cbc3c95fde11.jpg)

**Comment by marat2509** [comment]
It seems to work

**Comment by marat2509** [comment]
The proxies were updated, but the situation repeats itself, it just hangs and then the number of proxies becomes much smaller and the mining continues
![Screenshot_2021-06-05-21-17-57-716_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120901461-bcf1be00-c643-11eb-9912-a08b4fd02e3a.jpg)
![Screenshot_2021-06-05-21-18-12-127_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120901462-bebb8180-c643-11eb-990a-551d66f65f10.jpg)

**Comment by marat2509** [comment]
The speed is getting slower and slower

**Comment by Tenclea** [comment]
@marat2509 have you tried increasing the amount of threads in the config file ?

**Comment by marat2509** [comment]
> @marat2509 have you tried increasing the amount of threads in the config file ?

No, I used the default 1000 threads, which one should I try?

**Comment by Tenclea** [comment]
it depends on the performance of your computer  
I usually set it high enough for each proxy to be assigned a thread (in your case i guess it would be ~2500)

**Comment by marat2509** [comment]
2500 threads:
![Screenshot_2021-06-06-16-17-45-568_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120925774-c7af6000-c6e2-11eb-8cac-2fd36eeac9de.jpg)


I still cannot understand why after checking the proxy there are only a scanty number of them.

**Comment by marat2509** [comment]
3000 threads: (just freezes, then crashes)
![Screenshot_2021-06-06-16-49-21-183_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120926863-4ad2b500-c6e7-11eb-9d73-fc087e547448.jpg)

**Comment by Tenclea** [comment]
> 
> 
> 5000 threads: (just freezes, then crashes)
> ![Screenshot_2021-06-06-16-49-21-183_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120926863-4ad2b500-c6e7-11eb-9d73-fc087e547448.jpg)

This is most likely too much for your computer, so keep it at 2.5k

**Comment by Tenclea** [comment]
> 
> 
> 2500 threads:
> ![Screenshot_2021-06-06-16-17-45-568_com microsoft rdc androidx](https://user-images.githubusercontent.com/52219238/120925774-c7af6000-c6e2-11eb-8cac-2fd36eeac9de.jpg)
> 
> I still cannot understand why after checking the proxy there are only a scanty number of them.

So, first of all, the checker removes any proxy banned by discord. (it sends a request to a specific location, and if the answer is incorrect, the proxy is deleted)  
Then, if the connection to the proxy times out, it is removed as well. This means that if you have a slow internet connection, it might remove more proxies than someone with a good one.  
I have plans to allow users to change the proxy timeout in a future update, so make sure to keep an eye out for any notification on this repository ;)

I will be closing this issue for now, please let me know if you face any other problems :)
