### ISSUE TITLE
does this work for you

### ISSUE THREAD

**Issue by ItsiAdam** [Tenclea/YANG#32]
have you ever EVER got a working nitro code from this man

**Comment by bawdeveloppement** [comment]
Saying YES mean he used it so he should not answer you  😸

**Comment by Tenclea** [comment]
Just do the maths and evaluate your chances of finding a working code.  

My program is working, I have tested it multiple times with legally purchased, and working gift codes, so now, if you don't find any valid codes to leech, then you might want to get some good proxies or move on.

**Comment by ItsiAdam** [comment]
show me your math

**Comment by ItsiAdam** [comment]
you tested it with your own purchased giftcards wowo real impressive man

**Comment by ItsiAdam** [comment]
i could beat the shit out of you easily

**Comment by ItsiAdam** [comment]
you are insane

**Comment by ItsiAdam** [comment]
@Tenclea you cannot censor me mother f ucker
