### ISSUE TITLE
Please update the proxy server

### ISSUE THREAD

**Issue by tzt345** [Tenclea/YANG#33]
Plz

**Comment by Tenclea** [comment]
what do you mean ?

**Comment by tzt345** [comment]
I can't generate nitro codes :(

**Comment by Tenclea** [comment]
Well, if you have any other proxies provider feel free to send them, otherwise, I'd suggest buying some higher quality proxies yourself :)

**Comment by tzt345** [comment]
Ummmm
![Screenshot_2021-07-31-20-12-15-33_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/83703996/127739508-545eb5f6-e298-48c9-9968-35852ec684fb.png)

**Comment by tzt345** [comment]
I use termux

**Comment by Tenclea** [comment]
> 
> 
> I use termux

Good choice ;)

Regarding your issue, it looks like the app ran out of memory (ram). Try to lower the amount of threads or increase the memory allocated to the program.
