### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by tzt345** [Tenclea/YANG#34]
↑

**Comment by Tenclea** [comment]
First of all, you need to acknowledge that by using this tool, every code you'll find has been paid by someone else. So, i cannot advise you to use it.  

Second of all, and for all I know, when you claim a Discord gift code, nobody can see who claimed it.  

I hope this answered your question :)

**Comment by tzt345** [comment]
> First of all, you need to acknowledge that by using this tool, every code you'll find has been paid by someone else. So, i cannot advise you to use it.
> 
> Second of all, and for all I know, when you claim a Discord gift code, nobody can see who claimed it.
> 
> I hope this answered your question :)

K

**Comment by BasToTheMax** [comment]
> First of all, you need to acknowledge that by using this tool, every code you'll find has been paid by someone else. So, i cannot advise you to use it.
> 
> Second of all, and for all I know, when you claim a Discord gift code, nobody can see who claimed it.
> 
> I hope this answered your question :)

I think Discord itselfs can see it

**Comment by Tenclea** [comment]
> > First of all, you need to acknowledge that by using this tool, every code you'll find has been paid by someone else. So, i cannot advise you to use it.
> > 
> > Second of all, and for all I know, when you claim a Discord gift code, nobody can see who claimed it.
> > 
> > I hope this answered your question :)
> 
> I think Discord itselfs can see it 

They can actually,  but won't do anything unless the gift code is refunded, which would only revoke it on your side, without anything else happening
