### ISSUE TITLE
i runned on repl.it and i got this error

### ISSUE THREAD

**Issue by slowwdev** [Tenclea/YANG#35]
i runned on repl.it and i got this error

/home/runner/YANG/app.js:102
                if (!body?.message && !body?.subscription_plan) {
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by Tenclea** [comment]
To anyone having the same issue:  
Replit uses an outdaded version of Node.js, but there is a way to update it. [More info here](https://replit.com/talk/learn/How-to-update-Nodejs-version/143570)

**Comment by raVenoxis** [comment]
I updated but

**Comment by raVenoxis** [comment]
I updated but the proxies download stop after 208  proxies.
And i got a new error.
I think repl.it is really bad

**Comment by Tenclea** [comment]
Can you send what the error is ?

**Comment by raVenoxis** [comment]
just Failed To connect, retrying.

**Comment by raVenoxis** [comment]
__  _____________   __________
_ \/ /__    |__  | / /_  ____/
__  /__/ /| |_   |/ /_  / __  
_/ / _/ ___ |/ /|  / / /_/ /  
/_/  /_/  |_/_/ |_/  \____/   
       v2.4.0 - by Tenclea

17:27:36 [ERROR] » Invalid redeemToken: "token"
17:27:36 [INFO]  » Checking 17855 proxies... This might take up to 22 minutes.
17:28:24 [INFO]  » Proxies left: 15813 | Working: 145 | Time left: ~20 minutes      
<--- Last few GCs --->

[2673:0x488ac10]   169801 ms: Scavenge (reduce) 250.7 (256.5) -> 250.0 (257.5) MB, 1.6 / 0.0 ms  (average mu = 0.448, current mu = 0.296) allocation failure 
[2673:0x488ac10]   169817 ms: Scavenge (reduce) 250.9 (256.5) -> 250.2 (257.7) MB, 1.6 / 0.0 ms  (average mu = 0.448, current mu = 0.296) allocation failure 
[2673:0x488ac10]   171527 ms: Mark-sweep (reduce) 251.1 (256.7) -> 249.0 (257.7) MB, 1695.2 / 0.2 ms  (average mu = 0.376, current mu = 0.300) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xa25510 node::Abort() [Checking pr]
 2: 0x9664d3 node::FatalError(char const*, char const*) [Checking pr]
 3: 0xb9a8be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [Checking pr]
 4: 0xb9ac37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [Checking pr]
 5: 0xd56ca5  [Checking pr]
 6: 0xd8763e v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [Checking pr]
 7: 0xd93676 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [Checking pr]
 8: 0xd7f80f v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [Checking pr]
 9: 0xd7fa88 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [Checking pr]
10: 0xd72369 v8::internal::ItemParallelJob::Run() [Checking pr]
11: 0xd955d0 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [Checking pr]
12: 0xd95e6c v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [Checking pr]
13: 0xd96035 v8::internal::MarkCompactCollector::Evacuate() [Checking pr]
14: 0xda8031 v8::internal::MarkCompactCollector::CollectGarbage() [Checking pr]
15: 0xd642f8 v8::internal::Heap::MarkCompact() [Checking pr]
16: 0xd65de8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [Checking pr]
17: 0xd6922c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [Checking pr]
18: 0xd3790b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [Checking pr]
19: 0x107fbef v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [Checking pr]
20: 0x1426919  [Checking pr]
signal: aborted (core dumped)


**Comment by Tenclea** [comment]
Does this happen every time ?  
Can you try with a lower amount of threads ?

**Comment by raVenoxis** [comment]
Yes everytime.
What amount exacly?

**Comment by Tenclea** [comment]
Try to remove a 100 and if it still doesn't work, remove an additional 100, etc...

**Comment by slowwdev** [comment]
Doesnt works at all

**Comment by Tenclea** [comment]
How much RAM does your computer have ?

**Comment by slowwdev** [comment]
I use the free plan of replit

**Comment by Tenclea** [comment]
Well it seems like replit isn't made for this kind of tools
