### ISSUE TITLE
Any ways to add more proxies websites?

### ISSUE THREAD

**Issue by ScottsplaysSus** [Tenclea/YANG#36]
Hey Tenclea! Are there any ways to add new websites that scrape proxies? Because all of them just provides the IP address and doesn't include the https:// in front of the IP address.

**Comment by Tenclea** [comment]
Which websites are you trying to add ?  

The https:// part would be added automatically by YANG but only if the websites you added were correctly configured

**Comment by ScottsplaysSus** [comment]
I'm trying to add the websites below: 
1. https://openproxy.space/list
2. https://free-proxy-list.net/
3. https://www.proxyscan.io/
4. https://spys.one/en/
5. https://www.socks-proxy.net/
6. https://hidemy.name/en/proxy-list/

**Comment by ScottsplaysSus** [comment]
I also added a bunch of proxy IP addresses in the http-proxies.txt and socks-proxies.txt but all of those does not include the http(s):// or socks:// in front of the addresses.

**Comment by Tenclea** [comment]
> I also added a bunch of proxy IP addresses in the http-proxies.txt and socks-proxies.txt but all of those does not include the http(s):// or socks:// in front of the addresses.

This is fine, you don't have to add them

**Comment by ScottsplaysSus** [comment]
But one issue is that I added 14000+ http(s) proxies and 30000+ socks proxies but when I launch the .exe file it still detects 2000+ proxies. Is there any problem? 

Here are the files: 
[http-proxies.txt](https://github.com/Tenclea/YANG/files/7256875/http-proxies.txt)
[socks-proxies.txt](https://github.com/Tenclea/YANG/files/7256876/socks-proxies.txt)

**Comment by Tenclea** [comment]
> I'm trying to add the websites below: 
> 1. https://openproxy.space/list
> 2. https://free-proxy-list.net/
> 3. https://www.proxyscan.io/
> 4. https://spys.one/en/
> 5. https://www.socks-proxy.net/
> 6. https://hidemy.name/en/proxy-list/
> 

Most of these websites are not api links, which means the program would need to download the page and look for proxies there, which would be also more complicated.

On the other hand, some of them allow to download proxies directly through a link, which is what we need :)

I'll add the supported websites in the next  couple of hours, thanks for your contribution !

**Comment by ScottsplaysSus** [comment]
> But one issue is that I added 14000+ http(s) proxies and 30000+ socks proxies but when I launch the .exe file it still detects 2000+ proxies. Is there any problem?
> 
> Here are the files: [http-proxies.txt](https://github.com/Tenclea/YANG/files/7256875/http-proxies.txt) [socks-proxies.txt](https://github.com/Tenclea/YANG/files/7256876/socks-proxies.txt)


How about this issue? Can I fix it?

**Comment by ScottsplaysSus** [comment]
> > I'm trying to add the websites below:
> > 
> > 1. https://openproxy.space/list
> > 2. https://free-proxy-list.net/
> > 3. https://www.proxyscan.io/
> > 4. https://spys.one/en/
> > 5. https://www.socks-proxy.net/
> > 6. https://hidemy.name/en/proxy-list/
> 
> Most of these websites are not api links, which means the program would need to download the page and look for proxies there, which would be also more complicated.
> 
> On the other hand, some of them allow to download proxies directly through a link, which is what we need :)
> 
> I'll add the supported websites in the next couple of hours, thanks for your contribution !


No problem! Thanks for your reply too!

**Comment by Tenclea** [comment]
> 
> > But one issue is that I added 14000+ http(s) proxies and 30000+ socks proxies but when I launch the .exe file it still detects 2000+ proxies. Is there any problem?
> > 
> > Here are the files: [http-proxies.txt](https://github.com/Tenclea/YANG/files/7256875/http-proxies.txt) [socks-proxies.txt](https://github.com/Tenclea/YANG/files/7256876/socks-proxies.txt)
> 
> 
> How about this issue? Can I fix it?
> 

You should try to check whether there are duplicates among them on an online website or something

**Comment by ScottsplaysSus** [comment]
> > > But one issue is that I added 14000+ http(s) proxies and 30000+ socks proxies but when I launch the .exe file it still detects 2000+ proxies. Is there any problem?
> > > Here are the files: [http-proxies.txt](https://github.com/Tenclea/YANG/files/7256875/http-proxies.txt) [socks-proxies.txt](https://github.com/Tenclea/YANG/files/7256876/socks-proxies.txt)
> > 
> > 
> > How about this issue? Can I fix it?
> 
> You should try to check whether there are duplicates among them on an online website or something

After your advice, I had rechecked all the proxies for duplicates, now the list has 6148 http(s) proxies and 12153 socks proxies. Here are the files:
[http-proxies.txt](https://github.com/Tenclea/YANG/files/7257044/http-proxies.txt)
[socks-proxies.txt](https://github.com/Tenclea/YANG/files/7257045/socks-proxies.txt)

**Comment by Tenclea** [comment]
> > > > But one issue is that I added 14000+ http(s) proxies and 30000+ socks proxies but when I launch the .exe file it still detects 2000+ proxies. Is there any problem?
> > > > Here are the files: [http-proxies.txt](https://github.com/Tenclea/YANG/files/7256875/http-proxies.txt) [socks-proxies.txt](https://github.com/Tenclea/YANG/files/7256876/socks-proxies.txt)
> > > 
> > > 
> > > How about this issue? Can I fix it?
> > 
> > You should try to check whether there are duplicates among them on an online website or something
> 
> After your advice, I had rechecked all the proxies for duplicates, now the list has 6148 http(s) proxies and 12153 socks proxies. Here are the files:
> [http-proxies.txt](https://github.com/Tenclea/YANG/files/7257044/http-proxies.txt)
> [socks-proxies.txt](https://github.com/Tenclea/YANG/files/7257045/socks-proxies.txt)
> 
> The problem is, the exe still doesn't detect them and still uses 2498 proxies instead of the estimated 20000 total proxies... How can I fix this?

Can you create a new issue for that, it'll keep this issue clean. I'll be looking into it

**Comment by Tenclea** [comment]
Added the new proxies sites in b3cc9f2c58f062ca8c3600d95b8ad7b0b9a45038
