### ISSUE TITLE
App doesn't detect and doesn't uses proxies from the "http-proxies.txt" and "socks-proxies.txt"

### ISSUE THREAD

**Issue by ScottsplaysSus** [Tenclea/YANG#37]
The exe program doesn't detect and doesn't uses proxies from the "http-proxies.txt" and "socks-proxies.txt". How can I fix this? 

The .txt files:
[http-proxies.txt](https://github.com/Tenclea/YANG/files/7257769/http-proxies.txt)
[socks-proxies.txt](https://github.com/Tenclea/YANG/files/7257770/socks-proxies.txt)

**Comment by Tenclea** [comment]
Thank you for moving your issue, I will be looking into this

**Comment by Tenclea** [comment]
It's weird, everything seems to be working fine on my end..?  
Can you share your configuration file ?

**Comment by ScottsplaysSus** [comment]
Umm how can I share my configuration file? Where is it?

**Comment by Tenclea** [comment]
It should be the config.json file or config.yml if you upgraded to the latest version

**Comment by ScottsplaysSus** [comment]
umm GitHub says that they don't support that file so I screenshot it. Here you go. It's the config.yml file. 

![image](https://user-images.githubusercontent.com/91255736/135749457-ed2c91c5-bd13-45c2-9b05-515795503968.png)
![image](https://user-images.githubusercontent.com/91255736/135749465-2e885516-c66b-49b2-b183-1b550f912144.png)

**Comment by Tenclea** [comment]
Does the issue still occur after the next update ?

**Comment by Tenclea** [comment]
could you try to set the `enable_scrapper` variable of your config file to `false` ?

**Comment by ScottsplaysSus** [comment]
Alright, I made the ### enable_scrapper variable to ### false, and it shows 18K proxies. I think that the problem is solved.

**Comment by Tenclea** [comment]
Glad to hear that ! Have a wonderful day :)
