### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by BlackPyxl1** [Tenclea/YANG#41]
when it wanst to login with the token i get the this error : [ERROR] » Could not login using the provided redeemToken : Error: socket hang up

**Comment by Tenclea** [comment]
Does this happen every time ?

**Comment by BlackPyxl1** [comment]
> Does this happen every time ?

yes

**Comment by Tenclea** [comment]
Do you have a rather slow or fast internet speed on average ?

**Comment by Tenclea** [comment]
Closed until further replies
