### ISSUE TITLE
Won't check codes at all & will cause internet problems

### ISSUE THREAD

**Issue by XpioWolf** [Tenclea/YANG#46]
Node version: 17.2.0
npm version: 8.1.4
OS: FerenOS (ubuntbu based Linux distro)

When I run the program it all seems fine, checks proxys etc but then it will get stuck and won't check codes, and I can't connect to internet after running the program, I have to close terminal and restart computer. Ideas?

Also, thanks for making this.

**Comment by Tenclea** [comment]
Interesting. I never had the opportunity to test this project on Ubuntu so i'm going to need a little bit of help from your side.

Can you share your config settings ?  
Have you tried lowering the number of threads ? Try something around 100~200 at first.
Are the proxies yours, or do they come from public sources ?

**Comment by XpioWolf** [comment]
Lowering the threads fixed the issue, thanks!
