### ISSUE TITLE
(Not rly an issue) How to change the amount of proxies it finds?

### ISSUE THREAD

**Issue by ghost** [Tenclea/YANG#48]

**Comment by ZachyFrackyStudios** [comment]
This is from main clone and in the config.til file. When ever i add a value after the "proxies:" part, it refuses to work.

**Comment by Tenclea** [comment]
What kind of "value" are you trying to add ? Is it a proxies list ?

**Comment by ZachyFrackyStudios** [comment]
No the amount of proxies it finds

**Comment by Tenclea** [comment]
> No the amount of proxies it finds 

What does that mean ? How do you want to do this ?

**Comment by ZachyFrackyStudios** [comment]
![image](https://user-images.githubusercontent.com/86271733/147601277-a0f94183-cb8f-4174-8ad6-fdb0f72c9ca2.png)
Above me is the thing I want to edit, I assume this means something so when I add any value into it and run "node app.js" it crashes.****

**Comment by Tenclea** [comment]
You need another proxy source / website, or add your own into the provided proxy files, you won't be able to do anything using the config file.
