### ISSUE TITLE
Not running. "SyntaxError: Unexpected identifier"

### ISSUE THREAD

**Issue by codeisnotfunjk** [Tenclea/YANG#49]
![Screenshot 2022-02-02 11 15 05](https://user-images.githubusercontent.com/81317270/152192938-3b88e6d5-389f-42c2-bf58-c43671fe4347.png)
 
When entering "node app.js", this error message comes up. Is there a solution for this? #4

**Comment by Tenclea** [comment]
Make sure to upgrade your node version to 16.X or higher

**Comment by Tenclea** [comment]
It seems like the issue is more than likely coming from replit's side rather than this repo, you should check that all files were downloaded successfully, or contact replit support if the issue persists

**Comment by codeisnotfunjk** [comment]
Alright thanks for the reply.
