### ISSUE TITLE
Proxies Error 

### ISSUE THREAD

**Issue by Tirkovicc28** [Tenclea/YANG#5]
Just Purchased 110k Live Proxies re checked 2 times and ur checker is showing me i have only 40 proxies live idk when i re check them again i get 110k Live Proxies

**Comment by Tirkovicc28** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/77404943/111399777-57d2a000-86c6-11eb-978a-6fc82665c553.png)

**Comment by Tenclea** [comment]
> Just Purchased 110k Live Proxies re checked 2 times and ur checker is showing me i have only 40 proxies live idk when i re check them again i get 110k Live Proxies 

Some of them might have been banned from Discord's servers, or your network connection might be poor

**Comment by Tenclea** [comment]
> ![Screenshot_4](https://user-images.githubusercontent.com/77404943/111399777-57d2a000-86c6-11eb-978a-6fc82665c553.png)
> 

Well, this seems pretty clear, one of your proxies has a port bigger than what web ports actually support

**Comment by Tenclea** [comment]
@Tirkovicc28 Can I contact you on Discord somehow ?

**Comment by Tirkovicc28** [comment]
Tirkovic#5958
