### ISSUE TITLE
Don't find a working code 

### ISSUE THREAD

**Issue by mikejack99** [Tenclea/YANG#51]
Ive been testing for 2 days and don't find any working code. 

I use 6700 threads (about 1200 attempts per minute). 

This still working?

**Comment by Tenclea** [comment]
Yes the tool should still be working, but the time it takes for a valid code to be found usually takes many hours, if not days, as the probability to find one is very low.  

This is why having good proxies and an adequate amount of threads to go with them is the key to your luck :)
