### ISSUE TITLE
Threading gets  limited to proxy number + proxy  issues sometimes

### ISSUE THREAD

**Issue by kWAYTV** [Tenclea/YANG#53]
I've 1k  private proxies  from webshare and detects  them  as invalid in closely  every format but that's not a problem, the thing  is  that my  threads  get limited to the proxy  number

**Comment by kWAYTV** [comment]
also please  if u can  add new repos for proxies as paste.wtf has certificate expired

**Comment by Tenclea** [comment]
I see..  
Could you try checking your proxies with another proxy checker and tell me what the result is, i might need to dive again into my own proxy checker.

**Comment by Tenclea** [comment]
> also please  if u can  add new repos for proxies as paste.wtf has certificate expired

As for this, I'm taking care of it within the hour

**Comment by kWAYTV** [comment]
all my proxies are being used in all my other apps  without any problem, those are private and 100+

**Comment by Tenclea** [comment]
@kWAYTV what type are your proxies ? Are they socks ? Would you mind sending me a sample so that I test everything properly ?

**Comment by kWAYTV** [comment]
> 

Hey! they are  http proxies, yes i added you in discord few days ago!

**Comment by Tenclea** [comment]
Could you try to add me again ?

**Comment by Tenclea** [comment]
@kWAYTV Haven't heard from you in a while, could you add me on Discord so that we discuss about your issue ?
