### ISSUE TITLE
Is it possible to make the app run 24/7?

### ISSUE THREAD

**Issue by ScottsplaysSus** [Tenclea/YANG#63]
Hey Tenclea, its been a while, hope you still remember me :)

So my questions are:

Is it possible to host the app in an online server to let it run 24/7? And is it possible to do that for free? 

Also, is it possible to let it auto-update the app if a new version was released?

Thanks for this app once again, very cool :>

**Comment by Tenclea** [comment]
There are services such as [Replit](https://replit.com/) or [Heroku](https://www.heroku.com/) that let you host node.js instances for free. Although I'm not sure using brute-forcing tools is allowed, if you keep a low profile you should be fine.  
You could also check out [this npm package](https://www.npmjs.com/package/pm2)  which lets you monitor node apps running  on your machine, as well as auto starting them on boot if enabled.

Regarding the auto-update, I think Heroku has an option to deploy a GitHub repository, which will stay linked and auto update when changes are made. I cannot confirm this is also the case for Replit as I haven't used this website a lot.  

Anyways, I hope this will help you,
Have a nice day ! :)

**Comment by ScottsplaysSus** [comment]
Thanks for the reply, I will try those websites out when I am free :)
