### ISSUE TITLE
Low amount of proxies

### ISSUE THREAD

**Issue by Janko-007** [Tenclea/YANG#64]
Hello, I started that app and it downloaded me 23k proxies, can I ask how can I expand this number? Because only 540 works :/.
Thanks.

**Comment by Tenclea** [comment]
@Janko-007, Well, you could try to find/buy some online, which would most likely be much better than the free ones the generator scrapes from public sources.  
Also, make sure your thread count isn't too high because this often causes issues with the proxy checker if your internet speed isn't fast enough.  
Hope this helps, and have a great day ! :)

**Comment by Janko-007** [comment]
Okay, I have 45 download speed and 8 upload speed, good procesor ( 8 cores ). Would you recommend me what thread number can I use? Thanks

**Comment by Janko-007** [comment]
And can I ask, I finded the site but only with clear IPs like 193.32.231:2939 and where can I paste that? And there is any option to paste it without http:// or what's that like sock:// in the start? I mean I'm lazy to manually add that on 600 ips. Thanks

**Comment by Tenclea** [comment]
> Okay, I have 45 download speed and 8 upload speed, good procesor ( 8 cores ). Would you recommend me what thread number can I use? Thanks

This also depends on a lot of factors like how many people are connected to your network and the speed of your router, but I would suggest to set the thread number between 500-600 and try to increase little by little and see what gives the best results

**Comment by Tenclea** [comment]
> And can I ask, I finded the site but only with clear IPs like 193.32.231:2939 and where can I paste that? And there is any option to paste it without http:// or what's that like sock:// in the start? I mean I'm lazy to manually add that on 600 ips. Thanks

There are files in the `required` folder where you can paste them.

**Comment by Janko-007** [comment]
Can I paste it without that socks:// thing?

**Comment by Tenclea** [comment]
Yes you can, but make sure they are in the correct file. (Socks proxies in the socks file, http(s) in the http file)
