### ISSUE TITLE
I dont know why...

### ISSUE THREAD

**Issue by SkyShadowFlexX** [Tenclea/YANG#67]
![image](https://user-images.githubusercontent.com/67155778/168449832-7b8775e3-9f77-4b73-a1b1-f87c8e452121.png)

**Comment by Tenclea** [comment]
Is this the compiled version ?

**Comment by SkyShadowFlexX** [comment]
yes

**Comment by Tenclea** [comment]
@SkyShadowFlexX it should be fixed in the new version, try to redownload it
