### ISSUE TITLE
You're being rate limited

### ISSUE THREAD

**Issue by cojored** [Tenclea/YANG#68]
I got the "Your being rate limited please report this on github" message about 5 times in a row.

I set the thread count to 500 (it had no big difference in the number of codes per second)

**Comment by davidkra230** [comment]
a rate limit is where a server limits the amount of requests that can be made in a certain amount of time, since the amount of threads is set to 500 and "it had no big difference in the number of codes per second" then there must not be enough proxies to go around for each thread.

**Comment by Tenclea** [comment]
@cojored Is there a way i can contact you ? Via discord/telegram?

**Comment by cojored** [comment]
Yeah my discord is cojored#2177 @Tenclea

**Comment by Tenclea** [comment]
Fixed in v3.0.6
