### ISSUE TITLE
High CPU usage after some time of using it

### ISSUE THREAD

**Issue by AsbachAlfons** [Tenclea/YANG#75]
I have it set to 500 threads, and it starts off with around 10-15% cpu usage, but already after 45 minutes it is at 30-50% cpu usage. When letting it run overnight on my linux server it even reaches 100% cpu usage. Is there anything I can do to fix this?
![WindowsTerminal_WcY8lgiSWk](https://user-images.githubusercontent.com/102764201/178143082-c537aaec-bac3-4a65-a8ed-f4557f3715d2.png)

**Comment by Tenclea** [comment]
Are you running the compiled version or directly from source ?  
Can you try to run with a lower amount of threads ?  

I'll be doing some tests on my side and i'll let you know how it goes
@AsbachAlfons

**Comment by AsbachAlfons** [comment]
@Tenclea I downloaded it with git clone. So the one directly from source. I have tried lower threads too, but it seems to go up anyway.

**Comment by Tenclea** [comment]
@AsbachAlfons is this still an issue on the current version for you ? Have you tried updating nodejs ?

I can't seem to be able to reproduce your issue on my side

**Comment by AsbachAlfons** [comment]
I'll try it again right now. I will let you know.

**Comment by AsbachAlfons** [comment]
@Tenclea so after letting it run overnight it still goes up in cpu usage. Its not as much anymore, but it still went up to 60% overnight.

**Comment by Tenclea** [comment]
@AsbachAlfons I'm really pretty confident that this is a thread-related issue. Assuming that your internet speed isn't fast enough for all the requests to complete, the threads would pile up and cause some stress on your CPU.  
I guess you should try to lower the threads amount even more

**Comment by AsbachAlfons** [comment]
Alright, I'll try that.

**Comment by AsbachAlfons** [comment]
@Tenclea I now tried it with 250 threads, and it only went up to max 25% cpu. I guess this is the only fix for this.
