### ISSUE TITLE
Slow/stuck proxies check

### ISSUE THREAD

**Issue by MrTomatoYTe** [Tenclea/YANG#77]
Every time it starts checking, it will would just stuck there or check at a extremely pace. 
![Screenshot 2022-07-14 194815](https://user-images.githubusercontent.com/86038615/178975565-16cf68f7-5cc9-4697-8e55-507e802ca05a.png)
It is because I have bad internet connection or it's something else?

**Comment by Tenclea** [comment]
@MrTomatoYTe You should try lowering the amount of threads in the config file, find a number that would make it work. This is probably related to a slow internet connection, or your processor/router struggling to handle that many requests at a time

**Comment by Tenclea** [comment]
@MrTomatoYTe look on forums, or telegram groups / discord servers, etc...  
I'm sure there are a few gems hiding out there ;)
