### ISSUE TITLE
Feature Request: Proxy Pool functionality

### ISSUE THREAD

**Issue by Ninn0x4F** [Tenclea/YANG#79]
This is an amazing project and works pretty great so far with adjustments to threads / timeouts and even adding small webhooks:
![image](https://user-images.githubusercontent.com/8236957/180628590-ac8bd2e0-ab45-4957-ae78-b86a2afb748f.png)

Running it 24/7 currently

Now to the feature request, how hard would it be to add for example a "live" proxy pool? Let's say you want to keep it running 24/7 and if you get fresh proxies you want to obviously feed it with them, this currently forces to restart it, which triggers the proxy check again.

I thought of something like monitor every x minutes / seconds a file, if there are new proxies, add them to "proxies" and run a scan in another thread if possible and add them back to the current proxies list and then clear the file. Possibly even run a de-duplicate after adding them.

This would allow us to run the bot continously while adding fresh proxies easily.

However not sure how hard this will be to achieve in nodejs especially if it should run in another thread.

**Comment by Tenclea** [comment]
@Ninn0x4F I think in a way that this functionality is already implemented, as the proxy scrapper is triggered every half hour or so, and adds the downloaded proxies to the current list.

Yet, I wanted to ask you, what "tweaks" you made to the program, so that I can add them to the base app as well if you don't mind :)

**Comment by Ninn0x4F** [comment]
@Tenclea oh sorry I completely missed it but yes you are correct it is already there at the end of app.js checks every hour:
https://github.com/Tenclea/YANG/blob/97e863977a95ffc588c8e4f700aba98991de0e5e/app.js#L193

also uses the http-proxies and socks-proxies which is perfect and exactly what I was looking for :) Haven't really noticed it sry.

![image](https://user-images.githubusercontent.com/8236957/180667827-2575e33a-2ac9-4e50-b5c8-79d9dd82980a.png)

![image](https://user-images.githubusercontent.com/8236957/180667825-1ee1928e-30bf-4111-b7db-965fed5fb40a.png)

Regarding the tweaks, im using 2000 threads in the config file and multiplying the proxy scan by 2.5 so it uses 5000 threads for it. I am not really sure if only threads or the timeout affects it but sometimes the connections are just kept open and killed really really slowly, might be an issue with the proxy agent itself and not due the theards / timeouts: https://togithub.com/TooTallNate/node-https-proxy-agent/issues/53.

in app.js >
```js
if (config.proxies.enable_checker) proxies = await require('./utils/proxy-checker')(proxies, config.threads * 2.5);
	
//Webhook status update, 10s might generate too many messages 
setInterval(async () => {
	const attempts = stats.used_codes.length;
	const aps = attempts / ((+new Date() - stats.startTime) / 1000) * 60 || 0;
	const time = [new Date().getHours(), new Date().getMinutes(), new Date().getSeconds()].map(t => { if (t < 10) { t = '0' + t; } return t; });
	sendWebhook(config.webhook.url, `Proxies: \`${proxies.length + stats.threads}\` | Attempts: \`${attempts}\` (~\`${aps.toFixed(0)}\`/min) | Working Codes: ${stats.working}`);
	return;
}, 10000);
```

in proxy-checker.js >
```js		
let config = yaml.load(readFileSync('./config.yml'));
watchFile('./config.yml', () => {
	config = yaml.load(readFileSync('./config.yml'));
	return;
});

	//Adjusted the maxRetries to 4
	const maxRetries = 4;
	if (threads > proxies.length) threads = proxies.length;
	if (!silent) logger.info(`Checking ${chalk.yellow(proxies.length)} proxies... This might take up to ${ms((proxies.length * maxRetries * 15000) / threads, { long: true })}.`);

	let last = +new Date();
	
	proxies = await new Promise(complete => {
		const checkProxy = (p, ret = 0) => {
			const agent = new ProxyAgent(p); agent.timeout = 10000; //Set the agent timeout also to 10s
			needle.get('https://discordapp.com/api/v9/experiments', {
				agent: agent,
				follow: 10,
				response_timeout: 15000, //Increased timeout even if the proxy is slow we should use it and then app.js request can sort it out
				read_timeout: 8000, //Some just reply really slow but mostly useable
				rejectUnauthorized: false,
				....................................................................................................

	//Webhook status update, 10s might generate too many messages	
	const statusupdate = () => {

		if (silent) return;
		let eta = (((proxies.length + threads) * maxRetries * 15000) / threads) - (+new Date() - last);
		if (!eta || eta < 60_000) eta = 'less than a minute';
		else eta = '~' + ms(eta, { long: true });
			
		const time = [new Date().getHours(), new Date().getMinutes(), new Date().getSeconds()].map(t => { if (t < 10) { t = '0' + t; } return t; });
		sendWebhook(config.webhook.url, `Checking proxies... | Proxies left: \`${proxies.length + threads}\` | Working: \`${checked.length}\` | Time left: ${eta}`);
		return;
	};

	//Webhook status update, 10s might generate too many messages	
	const statusreport = setInterval(() => {
		if (threads <= 0) {
			clearInterval(statusreport);
		}
		statusupdate();
	}, 10000);
```

This at least doubled the active proxies for me. As the sometimes slower proxies would have been filtered out.

**Comment by Tenclea** [comment]
Wow o.o  
Thank you for the very detailled information, I'll make sure to take a deep dive when I have some time :)
