### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by Makergear25** [Tenclea/YANG#80]
Hello, 

I am having issues using it on macos I have downloaded node.js and everything but when I double click on the yang-macos it just opens as a text file, is there something I am doing wrong?

Sincerely,
Smellyboars

**Comment by Tenclea** [comment]
@Makergear25 Are you sure this is the correct way of opening executables on MacOS ? I haven't had the opportunity so far of using this os, but you should try to run a command prompt, and open up the file from there maybe

**Comment by Tenclea** [comment]
@Makergear25 Try typing `node app.js` instead
