### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by Ceeazer1** [Tenclea/YANG#81]
does the program support this proxy format?

hostname:port:username:password

**Comment by Ceeazer1** [comment]
I tried pasting them in the "required" folder and It didn't work

**Comment by Tenclea** [comment]
Try pasting them using the following format:

**Comment by Ceeazer1** [comment]
do I have to edit anything in the config file?

**Comment by Tenclea** [comment]
@Ceeazer1 no

**Comment by Ceeazer1** [comment]
ok thanks
