### ISSUE TITLE
Bun support

### ISSUE THREAD

**Issue by 0x454d505459** [Tenclea/YANG#84]
A new Javascript runtime came out recently and turns to be around 2 times faster than nodeJS.

Unfortunatelly it doesn't support some of the nodeJS and deno features YANG uses.

Might be a great idea to use it, or to at least add support for it. Im just saying ;)
It will required some work tho

 The current error:
 ```
 SyntaxError: Importing binding name 'EventEmitter' is not found.
      at YANG/node_modules/needle/lib/needle.js:9:26
      at bun:wrap:1:16354
      at YANG/app.js:5:18
 ```

**Comment by Tenclea** [comment]
I'd rather wait for the framework to implement all of Node's API functions before taking the time to adapt the whole tool for this specific framework
