### ISSUE TITLE
Some feedback in webhook

### ISSUE THREAD

**Issue by Spaceginner** [Tenclea/YANG#85]
So, if you enable webhook, it will not only send finded codes and startup, but also send every 1 hour (configurable) statistical info (so you will know it is alive), e.g. uptime, checked codes, finded codes, average code check rate over past 1 hour (depends on configured time delay for stat-message).

I want it to be, to know is it alive.

**Comment by Tenclea** [comment]
This is an idea I had in the back on my mind for a few weeks now. Thank  you for having created a reminder for me x)

I'll try to implement it in the next few days :)

**Comment by Spaceginner** [comment]
No problems, btw, have you used Heroku before? I am asking because I am getting error "...app couldnt bind to the $PORT within 60 seconds..." or something like that.  I think it is happening because Heroku waiting for it to bind but it wont because it doesnt need to bind, i guess. So, is there any hack or fix? (heroku scale web=0 worker=1 didnt work, or i am dumb)

**Comment by Tenclea** [comment]
> No problems, btw, have you used Heroku before? I am asking because I am getting error "...app couldnt bind to the $PORT within 60 seconds..." or something like that.  I think it is happening because Heroku waiting for it to bind but it wont because it doesnt need to bind, i guess. So, is there any hack or fix? (heroku scale web=0 worker=1 didnt work, or i am dumb)

Did you create a worker using `node app.js` ?

**Comment by Spaceginner** [comment]
I can't understand how to create a worker, I can't choose proccess "worker". And let's go to discord maybe, not sure

**Comment by Tenclea** [comment]
> I can't understand how to create a worker, I can't choose proccess "worker". And let's go to discord maybe, not sure

@Spaceginner check out #83

**Comment by Spaceginner** [comment]
Ok

**Comment by HarshalCODE** [comment]
> No problems, btw, have you used Heroku before? I am asking because I am getting error "...app couldnt bind to the $PORT within 60 seconds..." or something like that. I think it is happening because Heroku waiting for it to bind but it wont because it doesnt need to bind, i guess. So, is there any hack or fix? (heroku scale web=0 worker=1 didnt work, or i am dumb)

Instead of web : node app.js use worker : node app.js

**Comment by Spaceginner** [comment]
> > No problems, btw, have you used Heroku before? I am asking because I am getting error "...app couldnt bind to the $PORT within 60 seconds..." or something like that. I think it is happening because Heroku waiting for it to bind but it wont because it doesnt need to bind, i guess. So, is there any hack or fix? (heroku scale web=0 worker=1 didnt work, or i am dumb)
> 
> Instead of web : node app.js use worker : node app.js

Actually I did it, already, buuut, after a while (about 20 mins or so) it unlogins me and says "Cant find that user" (i ruined my main + twink acc already). And also, it seems like 128 threads is a limit because it runs out of memory.

**Comment by Tenclea** [comment]
Added in [fb97e82](https://github.com/Tenclea/YANG/commit/fb97e82ffd1a46fbe48d1e16f863784b97c80213) :)

**Comment by Spaceginner** [comment]
Wow, it took a while to make
