### ISSUE TITLE
Heroku Hosting

### ISSUE THREAD

**Issue by CyberVictoryMan** [Tenclea/YANG#86]
Can you make a tutorial / template to host this app on heroku

**Comment by Tenclea** [comment]
This is not an issue related to the program itself.

Heroku already has a well-written documentation on [how to setup a nodejs app](https://devcenter.heroku.com/articles/getting-started-with-nodejs), so make sure to check it out.

**Comment by CyberVictoryMan** [comment]
Um it doesn't even send me a msg thru webhook while hosted in heroku as worker: node app.js

**Comment by Tenclea** [comment]
> Um it doesn't even send me a msg thru webhook while hosted in heroku as worker: node app.js

@CyberVictoryMan Make sure your config file is properly edited, and check  the logs, otherwise it will not work.

**Comment by CyberVictoryMan** [comment]
The heroku does not support 1000 threads it just crashes the app sayin memory heap. But I tried with github workflow and it just works with 10000 threads and run for only 6 hours. Can you tell me the recommended thread count to get good performance going on1

**Comment by Tenclea** [comment]
@CyberVictoryMan find the working thread count through trial and error. Start with 100, if it works increase the number, if it doesn't, decrease it, and repeat until you find a satisfying number

**Comment by CyberVictoryMan** [comment]
Nope heroku doesnt like me. Ill better use github actions because I can create multiple instance with that. Maybe i will try one day and also can you increase the amount of proxies getting downloaded
