### ISSUE TITLE
Goes into the -0

### ISSUE THREAD

**Issue by baidjeet** [Tenclea/YANG#9]
![Screenshot 2021-05-04 081013](https://user-images.githubusercontent.com/83559672/117025947-32b6e280-acb0-11eb-8a05-8a2d68222c78.png)
Also have issues with speed and overall not getting any generated after running for at least a day at this point.

**Comment by Tenclea** [comment]
i am aware of the negative proxies issue and am investigation, i might revert to an older commit in the meantime.  
Regarding overall speed, you could try to buy some proxies, or maybe restart the generator every hour or so.  
Waiting a day for some nitro to be generated is not a lot. Actually, using codes of 16 in length, there are 16^52 unique codes to try out. So, at 4 attempts/s in your case, it will of course take some time lol

**Comment by Tenclea** [comment]
@baidjeet You might want to use this version for now : https://github.com/Tenclea/YANG/tree/bfbb2486e27474de9c7059cb13ebed35a2be8d24

**Comment by baidjeet** [comment]
> @baidjeet You might want to use this version for now : https://github.com/Tenclea/YANG/tree/bfbb2486e27474de9c7059cb13ebed35a2be8d24

I downloaded this version and I have the proxy auto scrape set to true but its asking me to put in proxies myself. Is this an issue with this version or I have something set up wrong?

**Comment by Tenclea** [comment]
@baidjeet yes it does  
but it does not support socks proxies

**Comment by Tenclea** [comment]
Should be fixed in the new update(s)
