### ISSUE TITLE
Could add a limit of proxies to download and check

### ISSUE THREAD

**Issue by TheDogHusky** [Tenclea/YANG#93]
Checking 10000+ proxies takes so much time, can we only like download 1000 proxies? I modified locally the code to have it, just slice the proxies variable (0, 1000).

But it would be better that it was in the config.yml.

**Comment by mobvote** [comment]
Hi, which file has this variable?

**Comment by TheDogHusky** [comment]
app.js

**Comment by mobvote** [comment]
What line?

**Comment by TheDogHusky** [comment]
39 and 52

**Comment by Tenclea** [comment]
Added in [dc7522f](https://github.com/Tenclea/YANG/commit/dc7522f04a677c942206d7bf15a9666d0a163f06) :)
